apiVersion: v2
kind: PersistentVolume
metadata:
  name: postgres-pv-0
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem

  accessModes:
  - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain
  storageclassName: manual
  hostPath:
    path: /data/postgres-1
